import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Assignment✨
        </h1>
          <h2 className='main'>InvoZone🟦</h2>

        <p className={styles.description}>
          Take A Look 🎉{' '}
        </p>

        <hr className="mx-auto text-blue-900  opacity-20 w-1/2 my-10"/>

            <h1 className={styles.title}>
            All About <a href="#">Events</a>🪄
          </h1>
            <h2 className='main'><div className="text-center mt-8">Events and their Required<br />Details. </div></h2>

          <p className={styles.description}>
            Take A Look 🎉
          </p>

          <div className={styles.grid}>
              <a href="http://localhost:3000/Event1" className={styles.card}>
                <h2><b>Synthetic Events</b>📤 &rarr;</h2>
                <p><b><i>What are synthetic events?</i></b> Take a look🎉</p>
              </a>

              <a href="http://localhost:3000/Event3" className={styles.card}>
                <h2><b>Event Usage</b>📤 &rarr;</h2>
                <p><b><i> I've made a little Project on Event handling. <br /> </i></b>Take a look🎉</p>
              </a>

            </div>  

            <hr className="mx-auto text-blue-900  opacity-20 w-1/2 my-10"/>

      <h1 className={styles.title}>
        Design <a href="#">Patterns</a>🪄
      </h1>
        <h2 className='main'><div className="text-center mt-8"> Explanation about some important <br /> Design patterns </div></h2>

      <p className={styles.description}>
        Take A Look 🎉
      </p>

      <div className={styles.grid}>
          <a href="http://localhost:3000/Design" className={styles.card}>
            <h2><b>Design Patterns</b>📤 &rarr;</h2>
            <p><b><i>Common Design Patterns</i></b> Take a look</p>
          </a>

          <a href="http://localhost:3000/Design2" className={styles.card}>
            <h2><b>Examples</b>📤 &rarr;</h2>
            <p>👈<b><i> Examples of those  <br />  </i></b>Take a look</p>
          </a>
        </div>

        <hr className="mx-auto text-blue-900  opacity-20 w-1/2 my-10"/>


        <h1 className={styles.title}>
          Coding <a href="#">Styles</a>🪄
        </h1>
          <h2 className='main'><div className="text-center mt-8">And Examples of some <br /> decorators as well</div></h2>

        <p className={styles.description}>
          Take A Look 🎉
        </p>

        <div className={styles.grid}>
          <a href="http://localhost:3000/impvdec" className={styles.card}>
            <h2><b>Coding Patterns</b>📤 &rarr;</h2>
            <p><b><i>Imperative / Declarative Pattern</i></b> Take a look</p>
          </a>

          <a href="http://localhost:3000/decorator" className={styles.card}>
            <h2><b>Decorator</b>📤 &rarr;</h2>
            <p>Decorator for <b><i> <br /> Imperative / Declarative Patterns </i></b>Take a look</p>
          </a>
        </div>
      </main>

      <hr className="mx-auto text-blue-900  opacity-20 w-1/2 my-10"/>


      <main className={styles.main}>
        <h1 className={styles.title}>
          Masonary <a href="#">Layout</a>🪄
        </h1>
          <h2 className='main'><div className="text-center mt-8">Tailwind, Flex, Grid, Float, <br /> Table, Positioning!</div></h2>

        <p className={styles.description}>
          Take A Look 🎉{' '}
        </p>

        <div className={styles.grid}>
          <a href="http://localhost:3000/about" className={styles.card}>
            <h2><b>TailWind CSS</b>📤 &rarr;</h2>
            <p>Submission for masonary grid, through <b><i> Tailwind CSS </i></b>Take a look</p>
          </a>

          <a href="http://localhost:3000/flex" className={styles.card}>
            <h2><b>FlexBox CSS</b>📤 &rarr;</h2>
            <p>Submission for masonary grid, through <b><i> FlexBox CSS </i></b>Take a look</p>
          </a>

          <a
            href="http://localhost:3000/float"
            className={styles.card}
          >
            <h2><b>Float CSS</b>📤&rarr;</h2>
            <p>Submission for masonary grid, through <b><i> Float CSS </i></b>Take a look</p>
          </a>

          <a
            href="http://localhost:3000/grid"
            className={styles.card}
          >
            <h2><b>Grid CSS</b>📤&rarr;</h2>
            <p>Submission for masonary grid, through <b><i> Grid CSS </i></b>Take a look</p>
          </a>
          
        </div>
     
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
